services:
  - type: web
    name: video-downloader-server
    env: node
    rootDir: server
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: /opt/render/project/src/.bun/bin:/opt/render/project/src/node_modules/.bin:/usr/local/bin:/usr/bin:/bin
    healthCheckPath: /status
    autoDeploy: true
    disk:
      name: temp
      mountPath: /opt/render/project/src/temp
      sizeGB: 1 