services:
  - type: web
    name: video-downloader-server
    env: node
    rootDir: server
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export PATH="/opt/render/project/src/.bun/bin:$PATH"
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: /opt/render/project/src/.bun/bin:/opt/render/project/src/node_modules/.bin:/usr/local/bin:/usr/bin:/bin
    healthCheckPath: /status
    autoDeploy: true
    disk:
      name: temp
      mountPath: /opt/render/project/src/temp
      sizeGB: 1 