services:
  - type: web
    name: video-downloader-server
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3.8 python3-pip ffmpeg
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin:/opt/render/project/src/node_modules/.bin
    healthCheckPath: /status
    autoDeploy: true
    disk:
      name: temp
      mountPath: /opt/render/project/src/temp
      sizeGB: 1 